//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veritabani2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projeEntities2 : DbContext
    {
        public projeEntities2()
            : base("name=projeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adres> Adres { get; set; }
        public DbSet<Bildirimler> Bildirimler { get; set; }
        public DbSet<Hayvanlar> Hayvanlar { get; set; }
        public DbSet<Kullanıcı> Kullanıcı { get; set; }
        public DbSet<Mahalle> Mahalle { get; set; }
        public DbSet<Sehirler> Sehirler { get; set; }
        public DbSet<Sokak> Sokak { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Veteriner> Veteriner { get; set; }
        public DbSet<Yemek> Yemek { get; set; }
    }
}
