//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veritabani2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hayvanlar
    {
        public int HayvanID { get; set; }
        public string Tür { get; set; }
        public string Yaş { get; set; }
        public string Kilo { get; set; }
        public string SağlıkDurum { get; set; }
        public string AşıDurum { get; set; }
        public string Adres { get; set; }
    }
}
