//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veritabani2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        public int KullanıcıID { get; set; }
        public string KullanıcıAd { get; set; }
        public string KullanıcıSoyad { get; set; }
        public string KullanıcıSifre { get; set; }
        public string KullanıcıGirişAdı { get; set; }
    }
}
