//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veritabani2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veteriner
    {
        public int VeterinerID { get; set; }
        public string Şehir { get; set; }
        public string Mahalle { get; set; }
        public string Sokak { get; set; }
        public string Çalışan { get; set; }
        public string HayvanTürleri { get; set; }
    }
}
