//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veritabani2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yemek
    {
        public Yemek()
        {
            this.Sokak = new HashSet<Sokak>();
        }
    
        public int YemekID { get; set; }
        public string Çeşit { get; set; }
        public string Miktar { get; set; }
        public string Açıklama { get; set; }
    
        public virtual ICollection<Sokak> Sokak { get; set; }
    }
}
